<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">HT</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?action=search">Tìm kiếm</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?action=papers">Báo mới</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <?php if (!(isset($_SESSION["IsLogined"]) && $_SESSION["IsLogined"] == True)) : ?>
                    <!-- Hiển thị liên kết đăng nhập nếu người dùng chưa đăng nhập -->
                    <li class="nav-item">
                        <a class="nav-link" href="Index.php?action=login">Login</a>
                    </li>
                <?php else : ?>
                    <!-- Hiển thị tên người dùng và menu thả xuống nếu người dùng đã đăng nhập -->
                    <li class="nav-item dropdown">  
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Hi, <?php echo htmlspecialchars($_SESSION["UserName"]); ?>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" href="index.php?action=profile">Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            <li><a class="dropdown-item" href="index.php?action=myPapers">My Papers</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="index.php?action=logout">Logout</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>