
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <?php require("include/meta.phtml"); ?>
</head>

<body>
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <h1 class="display-1 fw-bold">THÔNG BÁO</h1>
            <p class="fs-3"> <span class="text-danger">!!!</span> Bạn không có quyền truy cập vào trang này.</p>
            <a href="index.php" class="btn btn-primary">Về trang chủ</a>
        </div>
    </div>
</body>

</html>