<!-- TimKiemForm.phtml -->
<h1 class="mt-4">Tìm kiếm bài báo</h1>
<form action="index.php" method="GET" class="mt-3">
    <input type="hidden" name="action" value="search">
    <div class="form-group mb-2">
        <label for="keyword">Tiêu đề:</label>
        <input type="text" id="keyword" name="keyword" class="form-control">
    </div>
    <div class="form-group mb-2">
        <label for="author">Tác giả:</label>
        <input type="text" id="author" name="author" class="form-control">
    </div>
    <div class="form-group mb-2">
        <label for="conference">Tên hội nghị:</label>
        <input type="text" id="conference" name="conference" class="form-control">
    </div>
    <div class="form-group mb-2">
        <label for="time">Ngày:</label>
        <input type="date" id="time" name="time" class="form-control">
    </div>
    <div class="form-group mb-4">
        <label for="field">Tên Chủ đề:</label>
        <input type="text" id="field" name="field" class="form-control">
    </div>
    <div class="text-center mb-4">
    <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>
